"""make track id varchar

Revision ID: 75b815b25101
Revises: 2cac9b1224fb
Create Date: 2026-03-13 20:14:33.347788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75b815b25101'
down_revision: Union[str, None] = '2cac9b1224fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'track_id',
               existing_type=postgresql.ENUM('event', 'digital', 'communication', 'design', name='trackidenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tracks', 'id',
               existing_type=postgresql.ENUM('event', 'digital', 'communication', 'design', name='trackidenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tracks', 'id',
               existing_type=sa.String(),
               type_=postgresql.ENUM('event', 'digital', 'communication', 'design', name='trackidenum'),
               existing_nullable=False)
    op.alter_column('courses', 'track_id',
               existing_type=sa.String(),
               type_=postgresql.ENUM('event', 'digital', 'communication', 'design', name='trackidenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
