"""requires any for assignment

Revision ID: 99e46bdcfd54
Revises: 75b815b25101
Create Date: 2026-03-14 10:44:17.031625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e46bdcfd54'
down_revision: Union[str, None] = '75b815b25101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('requires_any', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'requires_any')
    # ### end Alembic commands ###
